### PR TITLE
Update entry.sh

### PR DESCRIPTION
**Pull request by nsanor**
Corrected the filepath for the base docker image entrypoint

### CODE REVIEW

**Comment by mcred** [comment]
Could you provide a failing use case? This action already runs in a docker context without failing. Can you provide your github action yaml?

**Comment by nsanor** [comment]
I tested the action on a private repo and it is not able to locate `docker-entrypoint.sh`. 

Output: 
> /entry.sh: line 122: docker-entrypoint.sh: command not found

Workflow yaml:
```
name: deploy-pending-changesets
on: 
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Test Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v1
        with:
          operation: 'status'
          classpath: './ETL/SQL'
          changeLogFile: 'changelog.xml'
          username: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          url: ${{ secrets.DB_URL }}
```

**Comment by nsanor** [comment]
It looks like the docker image changed the location of the entrypoint script between [3.10.3](https://hub.docker.com/layers/liquibase/liquibase/3.10.3/images/sha256-8a97f6818c2f10ea31b272b675c13f3f652737b7493fd1b84a09ac76298d2526?context=explore) and [4.1](https://hub.docker.com/layers/liquibase/liquibase/4.1/images/sha256-9d24b8126772450b2b574a407a11f8b5293a931989081ca82a38361d8cde1605?context=explore).

I was able to verify the change for the latest liquibase version by pulling the action code into my private repo.

**Comment by nsanor** [comment]
@mcred Any update on this?

**Comment by molivasdat** [comment]
@nsanor Working to fix the liquibase docker image instead to where docker-entrypoint.sh works whether you are using 3.10.3 or 4.2.2+ version of liquibase.

**Comment by nsanor** [comment]
@molivasdat Ok, thanks for the update. I'll close this PR.

**Pull request closed without merging**
